### ISSUE TITLE
Error after trying to read an uploaded file

### ISSUE THREAD

**Issue by alew3** [hviana/Upload-middleware-for-Oak-Deno-framework#2]
**this works**
.post("/classify", upload('image', ['jpg','png'], 20000000, 10000000, true),
    async (context: any, next: any) => {
        let filePath : string  = context.uploadedFiles['image']['uri']
        context.response.body = { msg: filePath }
    },
  )

Why do I get an error after trying to read the file? 
**this fails**
**Uncaught Error: The response is not writable.
      throw new Error("The response is not writable.");** 

.post("/classify", upload('image', ['jpg','png'], 20000000, 10000000, true),
    async (context: any, next: any) => {
        let filePath : string  = context.uploadedFiles['image']['uri']
        const image: Uint8Array = await Deno.readFile(filePath)
        context.response.body = { msg: filePath }
    },
  )

Also is there any way to use an in-memory uploaded file so I don't have to save it to disk?

**Comment by hviana** [comment]
Thanks. Fixed. With new options in middleware, use  saveFile = false and  readFile = true.

**Comment by hviana** [comment]
In your code, I believe that the error seems to be related to something from the oak

**Comment by hviana** [comment]
See: https://github.com/oakserver/oak/issues/148

**Comment by alew3** [comment]
> Thanks. Fixed. With new options in middleware, use saveFile = false and readFile = true.
Thanks for the quick correction!

I tried: 
.post("/classify", upload('image', ['jpg','png'], 20000000, 10000000, false, true)

I can now get the file in memory via 'data', but it still creates a file on the disk on the root folder.

**Comment by hviana** [comment]
This file is created by deno std. This avoids memory problems when multiple requests uploads are executed in same time. You can delete this file, like describle in readme: 
await Deno.remove(context.uploadedFiles['file2']['tempfile']). Fixed for tempfile don't stay in root. Thanks.
