### ISSUE TITLE
add git tags for versions

### ISSUE THREAD

**Issue by golavr** [hviana/Upload-middleware-for-Oak-Deno-framework#7]
std needs to be bumped to std@0.61.0 to run with deno v1.2
currently module have one branch/tag/version

![image](https://user-images.githubusercontent.com/22896741/87871926-39909500-c9bd-11ea-8d16-f92b9fffab86.png)

**Comment by hviana** [comment]
I updated the std branch, I think it will work now, but you need to test it. thank you.
