### ISSUE TITLE
This module needs a version to be published on denoland

### ISSUE THREAD

**Issue by GuilhermeVendramini** [hviana/Upload-middleware-for-Oak-Deno-framework#9]
No uploaded versions
This module name has been reserved for a repository, but no versions have been uploaded yet. Modules that do not upload a version within 30 days of registration will be removed. If you are the owner of this module, please re-add the GitHub repository with deno.land/x (by following the instructions at https://deno.land/x#add), and publish a new version.

**Comment by VijalPatel** [comment]
I am also getting same issue.
This one is major issue can you fix please

**Comment by hviana** [comment]
Fixed
